## Disabled

Lint/NotNil:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Naming/QueryBoolMethods:
  Enabled: false

Naming/BlockParameterName:
  Enabled: false

Style/NegatedConditionsInUnless:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

## Configured

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: true

Lint/SpecFilename:
  IgnoredDirs:
    - spec/spec_helper
    - spec/fixtures
