# run continuous deployment pipeline on every push on a tag in the form "v0.0.0"
on:
  push:
    tags:
      - "v*.*.*"

# deploy to github's image registry
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# run build-and-push job and deploy-docs jobs on an ubuntu host
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.19.1
      - name: Install libraries
        run: sudo apt update && sudo apt install -y lld
      - name: Cache shards
        uses: actions/cache@v5
        with:
          path: lib
          key: shards-${{ runner.os }}-${{ hashFiles('shard.lock') }}
          restore-keys: |
            shards-${{ runner.os }}-
      - name: Install shards
        run: shards install
      - name: Generate docs
        run: crystal docs
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:       
    
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Gather docker meta information
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha    

      # build ktistec using the version of the current tag
      - name: Build and push docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            version=v${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
