# run continuous deployment pipeline on every push on a tag in the form "v0.0.0"
on:
  push:
    tags:
      - "v*.*.*"

# deploy to github's image registry
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# run build-and-push job on an ubuntu host
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write

    steps:       
    
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Gather docker meta information
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha    

      # build ktistec using the version of the current tag
      - name: Build and push docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            version=v${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
